[package]
name = "hvm"
version = "0.1.6"
edition = "2021"
description = "A lazy, beta-optimal, massively-parallel, non-garbage-collected and strongly-confluent functional compilation target."
repository = "https://github.com/Kindelia/HVM"
license = "MIT"
keywords = ["functional", "language", "runtime", "compiler", "target"]
categories = ["compilers"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
test = true

[[bin]]
name = "hvm"
test = false

[dependencies]
num_cpus = "1.13"
itertools = "0.10"
nom = "7.1"
nom_locate = "4.0"
